### ISSUE TITLE
Fale com a Comunidade

### ISSUE THREAD

**Issue by abpaula77** [dev-pira/site#125]
Vamos fazer no formato de _live Coding_ em 15/6 o/

**Comment by abpaula77** [comment]
Adicionar seção fale com a Comunidade.
Contato
Membros da comunidade

**Comment by murilobeltrame** [comment]
Como mandar email via NextJs.
Dica do @gabrielcesar95 , podemos usar o SMTP da nossa hospedagem ao invés de Gmail como no exemplo

**Comment by murilobeltrame** [comment]
@gabrielcesar95 , https://nodemailer.com/about/ tem exemplos de como enviar para email via Node:
Sugestão de fluxo:
Página com Form-> API -> NodeMailer -> SMTPzão do Gmail se pah ....
