### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by abpaula77** [dev-pira/site#131]
atualizar o Favicon do site (icone da guia/aba do site)

**Comment by jhonymiler** [comment]
qual cor? Preto com o icone branco, branco com o icone, preto..

**Comment by abpaula77** [comment]
Fundo preto com ícone branco acho que fica melhor nos modos escuros

Em dom., 25 de jun. de 2023 13:15, Jonatas Miler Oliveira <
***@***.***> escreveu:
