### ISSUE TITLE
Implementar linter

### ISSUE THREAD

**Issue by gabrielcesar95** [dev-pira/site#152]
Tenho tido muitas dificuldades no que se refere a indentação do código 
O principal é a falta de referência para a indentação automática da IDE. É possível configurar o VSCode pra identar a cada ctrl+s.
Além de facilitar a vida, isso resolve o problema abaixo, que tbm já vi no repositório:

**Arquivo A**
```typescript
<componente>
  <filho>
  </filho>
<componente>
```

**Arquivo B**
```typescript
<componente>
    <filho>
    </filho>
<componente>
```

Julgo essa como uma tarefa prioritária, pro caso de recebermos colaborações de pessoas _de fora_

**Comment by murilobeltrame** [comment]
Resolved by #153
