### ISSUE TITLE
Quantidade de eventos na seção de eventos

### ISSUE THREAD

**Issue by abpaula77** [dev-pira/site#155]
https://www.devpira.com.br/eventos/devpira-festival-2022

O evento do link acima existe mas não é mostrado na lista de eventos.
A seção de eventos está mostrando apenas 4 eventos e não está abrindo uma linha adicional quando existem mais de 4 eventos.

**Comment by murilobeltrame** [comment]
Já foi corrigido.
Como? Por quem? Que dia? 
Não sabemos .... kkkkk
