### ISSUE TITLE
Conteúdo HTML inline nos conteúdos de descrição do evento

### ISSUE THREAD

**Issue by abpaula77** [dev-pira/site#65]
Na seção da descrição "Sobre o evento" na parte "Participe", "Outras Informações" referente a doação de alimentos.
Adicionar um link para www.piauniao.com.br no nome "Pia União de Santo Antônio."

**Comment by murilobeltrame** [comment]
Cara, achei legal a ideia, mas num tenho uma vaga ideia de como faria para isso funcionar.
Explicando: Os dados do evento são carregados de um arquivo `json` e futuramente através de um CMS.
Não to conseguindo pensar num jeito fácil de transformar o texto que carrega na página em um link ....
