### ISSUE TITLE
Página de vagas

### ISSUE THREAD

**Issue by murilobeltrame** [dev-pira/site#88]

**Comment by murilobeltrame** [comment]
- [ ] Criar uma estrutura de dados especifica para Vagas
- [ ] Criar o componente cabeçalho para Vagas
- [ ] Criar o componente "Cartão da Vaga"
- [ ] Criar o componente de Vagas
- [ ] Criar a página

**Comment by abpaula77** [comment]
Criar uma estrutura de dados especifica para Vagas?

Vaga
------------------
id int
Proprietario_id int
Titulo da Vaga string20
Descrição text
Salario float
Validade datetime
email string50
link string255

Proprietario
------------------
id int
Nome string100
empresa string100 (empresa id?)
email string50
site string100

Nivel
------------------
Estagiario
Junior
Pleno
Senior
Arquiteto

Domínios / Sub-Domínios
------------------
Backend
Frontend
Fullstack
PO
PM
SM
------------------
ou
------------------
Delphi
PHP
.NET
Node.JS
Paint
